name: OurMessageBoard
version: 0.0.1
description: Team work comes out
dependencies:
  browser: any
  messenger: "^0.0.7"
  polymer: ">=0.15.1 <0.17.0"
  sqljocky: "^0.14.1"
dev_dependencies:
  unittest: any