name: OurMessageBoard
version: 0.0.1
description: Team work comes out
dependencies:
  browser: any
  messenger: "^0.0.7"
  sqljocky: "^0.14.1"
  rest_frame: "^0.1.1"
  dialog: "^0.5.0"
  dnd: "^0.3.0"
dev_dependencies:
  unittest: any